### ISSUE TITLE
Site is not loading :(

### ISSUE THREAD

**Issue by LauraWae** [lingdb/soundcomparisons#255] opened 2015-10-28 12:49 UTC

**Comment by runjak** [comment] 2015-10-28 13:40
![loading](https://cloud.githubusercontent.com/assets/5417642/10790081/8624a7d6-7d81-11e5-810b-456f63d1a375.png)
Presumably you get a situation where the menu shows up, but the loading bar doesn't disappear.
I have this same problem, too.
The reason here appears to be that the MapView is somehow broken (looks like google maps got an update and the current code doesn't work in relation to it.).
As a work around you can do the following:

1. Use the TopMenu to click on one of the other views.
2. Notice that this click changes the displayed URL in your browsers URL bar.
3. Focus the URL bar and hit `enter` to reload the page with that URL.

Apart from MapView the page should than work.
I'll see to get this issue fixed soon.

**Comment by runjak** [comment] 2015-10-30 12:48
I've added this to the `flask integration` milestone as this problem should automatically disappear once the flask version of the site is running.

**Comment by runjak** [comment] 2015-12-10 15:06
I just tested both the current deployment and the upcoming page I'm working on, and could no longer reproduce the problem in firefox or chromium. I'll therefore close this issue.

**Closed by runjak** 2015-12-10 15:06 UTC
Labels: bug
